export {
    default as CommandoClient,
    CommandoClientEvents,
    CommandoClientOptions,
} from './client';
export {
    default as CommandoRegistry,
    CommandGroupResolvable,
    CommandResolvable,
    DefaultCommandsOptions,
    DefaultTypesOptions,
    RequireAllOptions,
} from './registry';
export { default as CommandDispatcher, Inhibition } from './dispatcher';
export { default as SettingProvider, SettingProviderGet } from './providers/base';
export { default as GuildSettingsHelper } from './providers/helper';
export { default as SQLiteProvider, DefaultSQLiteSettings } from './providers/sqlite';
export { default as SyncSQLiteProvider } from './providers/sqlite-sync';
export {
    default as CommandoInteraction,
    SlashCommandBasicOptionsParser,
    SlashCommandOptionTypeMap,
} from './extensions/interaction';
export { default as CommandoGuild } from './extensions/guild';
export {
    default as CommandoMessage,
    CommandContextChannel,
    CommandoMessageResponse,
    ResponseOptions,
    ResponseType,
    StringResolvable,
} from './extensions/message';
export {
    default as Command,
    APISlashCommand,
    ArgumentTypeToSlashMap,
    CommandArgumentsResolvable,
    CommandBlockData,
    CommandBlockReason,
    CommandContext,
    CommandInfo,
    SlashCommandInfo,
    Throttle,
    ThrottlingOptions,
} from './commands/base';
export { default as CommandGroup } from './commands/group';
export {
    default as ArgumentCollector,
    ArgumentCollectorResult,
    ParseRawArguments,
} from './commands/collector';
export {
    default as Argument,
    ArgumentDefault,
    ArgumentInfo,
    ArgumentInfoResolvable,
    ArgumentResponse,
    ArgumentResult,
    ArgumentTypeString,
    ArgumentTypeStringMap,
    ReadonlyArgumentInfo,
} from './commands/argument';
export { default as ArgumentType } from './types/base';
export { default as ArgumentUnionType } from './types/union';
export { default as FriendlyError } from './errors/friendly';
export { default as CommandFormatError } from './errors/command-format';
export { default as ClientDatabaseManager } from './database/ClientDatabaseManager';
export { default as DatabaseManager, QuerySchema, DatabaseFetchOptions } from './database/DatabaseManager';
export { default as GuildDatabaseManager } from './database/GuildDatabaseManager';
export {
    ActiveSchema,
    AfkSchema,
    AnySchema,
    BaseSchema,
    BaseSchemaWithTimestamps,
    BaseSchemaWithoutTimestamps,
    DisabledSchema,
    DocumentFrom,
    ErrorSchema,
    FaqSchema,
    GuildAuditLog,
    GuildModule,
    JSONIfySchema,
    McIpSchema,
    ModelFrom,
    ModerationSchema,
    ModerationType,
    ModuleSchema,
    PollSchema,
    PrefixSchema,
    ReactionRoleSchema,
    ReminderSchema,
    RuleSchema,
    SchemaResolvable,
    SetupSchema,
    StickyRoleSchema,
    TimeBasedModerationType,
    TodoSchema,
    WelcomeSchema,
} from './database/Schemas';
export {
    default as Util,
    AbstractConstructable,
    Commandoify,
    CommandoifyMessage,
    Constructable,
    Destructure,
    Mutable,
    NonAbstractConstructable,
    OverrideClient,
    OverrideGuild,
    PropertiesOf,
    Require,
    SplitOptions,
    Tuple,
} from './util';
export type {
    AnyCommandoSelectMenuInteraction,
    AnyCommandoThreadChannel,
    BaseCommandoGuildEmojiManager,
    CommandoAutoModerationActionExecution,
    CommandoAutoModerationRule,
    CommandoAutocompleteInteraction,
    CommandoButtonInteraction,
    CommandoCategoryChannel,
    CommandoChannel,
    CommandoChannelManager,
    CommandoChannelResolvable,
    CommandoChannelSelectMenuInteraction,
    CommandoChatInputCommandInteraction,
    CommandoCommandInteraction,
    CommandoContextMenuCommandInteraction,
    CommandoDMChannel,
    CommandoEmojiResolvable,
    CommandoForumChannel,
    CommandoGuildBan,
    CommandoGuildBasedChannel,
    CommandoGuildChannel,
    CommandoGuildChannelManager,
    CommandoGuildChannelResolvable,
    CommandoGuildEmoji,
    CommandoGuildEmojiManager,
    CommandoGuildManager,
    CommandoGuildMember,
    CommandoGuildMemberManager,
    CommandoGuildMemberResolvable,
    CommandoGuildResolvable,
    CommandoGuildScheduledEvent,
    CommandoGuildTextBasedChannel,
    CommandoInteractionOverride,
    CommandoInvite,
    CommandoMappedChannelCategoryTypes,
    CommandoMentionableSelectMenuInteraction,
    CommandoMessageComponentInteraction,
    CommandoMessageContextMenuCommandInteraction,
    CommandoMessageReaction,
    CommandoModalMessageModalSubmitInteraction,
    CommandoModalSubmitInteraction,
    CommandoNewsChannel,
    CommandoPresence,
    CommandoPrivateThreadChannel,
    CommandoPublicThreadChannel,
    CommandoRepliableInteraction,
    CommandoRole,
    CommandoRoleManager,
    CommandoRoleResolvable,
    CommandoRoleSelectMenuInteraction,
    CommandoStageChannel,
    CommandoStageInstance,
    CommandoSticker,
    CommandoStringSelectMenuInteraction,
    CommandoTextBasedChannel,
    CommandoTextChannel,
    CommandoTextChannelResolvable,
    CommandoThreadChannel,
    CommandoThreadMember,
    CommandoTyping,
    CommandoUser,
    CommandoUserContextMenuCommandInteraction,
    CommandoUserResolvable,
    CommandoUserSelectMenuInteraction,
    CommandoVoiceBasedChannel,
    CommandoVoiceChannel,
    CommandoVoiceState,
    CommandoifiedInteraction,
    CommandoifiedMessage,
    FetchCommandoMemberOptions,
    FetchCommandoMembersOptions,
    FetchedCommandoThreads,
    NonThreadCommandoGuildBasedChannel,
    OverwrittenClientEvents,
    PartialCommandoDMChannel,
    PartialCommandoGroupDMChannel,
    PartialCommandoGuildMember,
    PartialCommandoThreadMember,
    PartialCommandoUser,
    PartialCommandoifiedMessage,
} from './discord.overrides';

declare function require<T>(id: string): T;
export const version = require<{ version: string }>('../package.json').version;
